name: Node Nasa-API CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --prefix client
      - run: npm i fixed postcss-safe-parser --prefix client
      - run: npm install --prefix server
      - run: npm run build --prefix client
      - run: npm test --prefix server