name: Node Nasa-API CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs V16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install --prefix client
      - run: npm install --prefix server
      - run: npm run build --prefix client